apiVersion: v1
kind: Service
metadata:
  name: {{ include "myrdp.fullname" . }}
  labels:
    {{- include "myrdp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rdp
      protocol: TCP
      name: rdp
  selector:
    {{- include "myrdp.selectorLabels" . | nindent 4 }}
