apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysmb.fullname" . }}
  labels:
    {{- include "mysmb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smb
      name: smb    
  selector:
    {{- include "mysmb.selectorLabels" . | nindent 4 }}
