apiVersion: v1
kind: Service
metadata:
  name: {{ include "myssh.fullname" . }}
  labels:
    {{- include "myssh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "myssh.selectorLabels" . | nindent 4 }}
